# Generated by Django 2.1 on 2019-03-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_in_miles', models.FloatField()),
                ('speed', models.FloatField()),
            ],
            options={
                'ordering': ('-distance_in_miles',),
            },
        ),
    ]
