# Generated by Django 2.1 on 2019-03-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RunKeeper', '0003_auto_20190303_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_dist',
        ),
    ]
