# Generated by Django 2.1 on 2019-03-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RunKeeper', '0004_auto_20190303_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='speed',
            new_name='length_of_run',
        ),
    ]
